### PR TITLE
Some bugfixes

### PR DESCRIPTION
**Pull request by adrido**
The single commits says all. I would be happy if this can be merged, because it fixes some annoying bugs. Thanks

### CODE REVIEW

**Comment by VanessaE** [comment]
Most stuff looks fine, but on-rightclick to change the state is intentional, as most other things in Minetest operate the same way, and there is an on-punch handler in Unified Dyes that's used to color the nodes.

**Comment by adrido** [comment]
Well the original boblocks did use the on_punch so I thought its the best idea to keep that. And I was not sure what handler to use, because you sometimes had the on_punch and sometimes the on_rightclick callback for swapping used. That made it very uncomfortable. Which one should used now?

**Comment by VanessaE** [comment]
I do apologize for the confusion.  It was necessary to change Bobblocks to use on_rightclick for state change because Unified Dyes needs on_punch for coloring.

You should use on_rightclick, and don't define any on_punch at all (in essence, delete commit 9e32b977b750c4ebd6a095357efc2a25cd36bb8f from your pull request).

**Comment by adrido** [comment]
Done.
Deleting was not the solution, because then there would be still this line: https://github.com/minetest-mods/BobBlocks/blob/master/blocks.lua#L51
But i rebased it to always use on_rightclick

**Comment by VanessaE** [comment]
Good catch, I must have forgot that one.

**Pull request merged**
